name: Auto format README.md 
on:
  push:
    branches:
      - main

jobs:
  sort-projects:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          

      - name: Run script
        run: |
          python .github/scripts/format_projects.py
          
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git diff --cached --quiet || git commit -m "🤖 Format README.md"
          git push